"""OpenCV preprocessing, fixture, and fire-candidate detection components."""

from firesentinel.vision.fixtures import (
    FIXTURE_SEED,
    FIXTURE_SHAPE,
    FIXTURE_VERSION,
    NUMERIC_TOLERANCES,
    OFFLINE_MANIFEST_PATH,
    ExpectedComponent,
    FixtureIntegrityError,
    FrameQualityExpectation,
    NumericTolerances,
    PersistenceExpectation,
    SyntheticFixtureBundle,
    SyntheticFixtureCase,
    fixture_bundle_digest,
    fixture_case_digests,
    generate_synthetic_fixture_bundle,
    load_offline_fixture_bundle,
    offline_fixture_manifest,
    verify_fixture_bundle,
)
from firesentinel.vision.quality import (
    DEVELOPMENT_QUALITY_THRESHOLDS,
    THRESHOLD_SELECTION_SCOPE,
    ObservationQuality,
    ObservationQualityThresholds,
    apply_quality_gate,
    measure_observation_quality,
    measure_prepared_tile_quality,
)
from firesentinel.vision.tiles import (
    PreparedTile,
    TilePreparationParameters,
    prepare_calibrated_tile,
    prepare_tile,
)

__all__ = [
    "FIXTURE_SEED",
    "FIXTURE_SHAPE",
    "FIXTURE_VERSION",
    "NUMERIC_TOLERANCES",
    "OFFLINE_MANIFEST_PATH",
    "ExpectedComponent",
    "FixtureIntegrityError",
    "FrameQualityExpectation",
    "NumericTolerances",
    "PersistenceExpectation",
    "SyntheticFixtureBundle",
    "SyntheticFixtureCase",
    "fixture_bundle_digest",
    "fixture_case_digests",
    "generate_synthetic_fixture_bundle",
    "load_offline_fixture_bundle",
    "offline_fixture_manifest",
    "verify_fixture_bundle",
    "PreparedTile",
    "TilePreparationParameters",
    "prepare_calibrated_tile",
    "prepare_tile",
    "DEVELOPMENT_QUALITY_THRESHOLDS",
    "THRESHOLD_SELECTION_SCOPE",
    "ObservationQuality",
    "ObservationQualityThresholds",
    "apply_quality_gate",
    "measure_observation_quality",
    "measure_prepared_tile_quality",
]
